const { ObjectId } = require("mongoose").Types;

const sampleMemes = [
  {
    title: "Bombardiro Crocodilo",
    imageUrl: "https://gateway.pinata.cloud/ipfs/QmX1BombardiroCroc",
    description: "A viral meme of a crocodile flying like a chopper.",
    creatorId: new ObjectId(),
    mintedBy: [new ObjectId()],
    memeLevel: "Legendary",
    popularityScore: 92.3,
    category: "Animal",
    tags: ["crocodile", "viral", "funny"],
    mintedAt: Date.now(),
  },
  {
    title: "Shark in Sneakers",
    imageUrl: "https://gateway.pinata.cloud/ipfs/QmY2SharkSneakers",
    description: "When sharks decide to flex their streetwear.",
    creatorId: new ObjectId(),
    mintedBy: [new ObjectId()],
    memeLevel: "Epic",
    popularityScore: 78.5,
    category: "Animal",
    tags: ["shark", "sneakers", "street"],
    mintedAt: Date.now(),
  },
  {
    title: "Cat CEO",
    imageUrl: "https://gateway.pinata.cloud/ipfs/QmZ3CatCEO",
    description: "This cat runs a startup, and it's killing it.",
    creatorId: new ObjectId(),
    mintedBy: [new ObjectId()],
    memeLevel: "Rare",
    popularityScore: 65.0,
    category: "Animal",
    tags: ["cat", "ceo", "startup"],
    mintedAt: Date.now(),
  },
  {
    title: "Helicopter Hamster",
    imageUrl: "https://gateway.pinata.cloud/ipfs/QmA4HamsterChopper",
    description: "Hamster takes flight in DIY chopper mode.",
    creatorId: new ObjectId(),
    mintedBy: [new ObjectId()],
    memeLevel: "Epic",
    popularityScore: 81.7,
    category: "Animal",
    tags: ["hamster", "helicopter", "cute"],
    mintedAt: Date.now(),
  },
  {
    title: "Panda DJ",
    imageUrl: "https://gateway.pinata.cloud/ipfs/QmB5PandaDJ",
    description: "Panda spinning tracks in the bamboo club.",
    creatorId: new ObjectId(),
    mintedBy: [new ObjectId()],
    memeLevel: "Rare",
    popularityScore: 55.2,
    category: "Animal",
    tags: ["panda", "dj", "music"],
    mintedAt: Date.now(),
  },
  {
    title: "Giraffe in Glasses",
    imageUrl: "https://gateway.pinata.cloud/ipfs/QmC6GiraffeSpecs",
    description: "Giraffe sees the world in style.",
    creatorId: new ObjectId(),
    mintedBy: [new ObjectId()],
    memeLevel: "Common",
    popularityScore: 32.9,
    category: "Animal",
    tags: ["giraffe", "glasses", "fashion"],
    mintedAt: Date.now(),
  },
  {
    title: "Rocket Raccoon",
    imageUrl: "https://gateway.pinata.cloud/ipfs/QmD7RaccoonRocket",
    description: "Raccoon launches into orbit for snacks.",
    creatorId: new ObjectId(),
    mintedBy: [new ObjectId()],
    memeLevel: "Epic",
    popularityScore: 84.4,
    category: "Animal",
    tags: ["raccoon", "rocket", "space"],
    mintedAt: Date.now(),
  },
  {
    title: "Penguin Pilot",
    imageUrl: "https://gateway.pinata.cloud/ipfs/QmE8PenguinPilot",
    description: "Penguin takes control of the cockpit.",
    creatorId: new ObjectId(),
    mintedBy: [new ObjectId()],
    memeLevel: "Rare",
    popularityScore: 60.1,
    category: "Animal",
    tags: ["penguin", "pilot", "aviation"],
    mintedAt: Date.now(),
  },
  {
    title: "Elephant Skateboarder",
    imageUrl: "https://gateway.pinata.cloud/ipfs/QmF9ElephantSkate",
    description: "Elephant shows off moves at the skate park.",
    creatorId: new ObjectId(),
    mintedBy: [new ObjectId()],
    memeLevel: "Epic",
    popularityScore: 73.8,
    category: "Animal",
    tags: ["elephant", "skateboard", "sport"],
    mintedAt: Date.now(),
  },
  {
    title: "Ninja Fox",
    imageUrl: "https://gateway.pinata.cloud/ipfs/QmG10FoxNinja",
    description: "This fox disappears in a puff of smoke.",
    creatorId: new ObjectId(),
    mintedBy: [new ObjectId()],
    memeLevel: "Legendary",
    popularityScore: 95.6,
    category: "Animal",
    tags: ["fox", "ninja", "stealth"],
    mintedAt: Date.now(),
  },
];

module.exports = { data: sampleMemes };
